//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.SemanticAnalysisService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SemanticAnalysisService.ISemanticAnalysisService")]
    public interface ISemanticAnalysisService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISemanticAnalysisService/Analyze", ReplyAction="http://tempuri.org/ISemanticAnalysisService/AnalyzeResponse")]
        Service.TextAnalysisResult Analyze(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISemanticAnalysisService/Analyze", ReplyAction="http://tempuri.org/ISemanticAnalysisService/AnalyzeResponse")]
        System.Threading.Tasks.Task<Service.TextAnalysisResult> AnalyzeAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISemanticAnalysisServiceChannel : Client.SemanticAnalysisService.ISemanticAnalysisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SemanticAnalysisServiceClient : System.ServiceModel.ClientBase<Client.SemanticAnalysisService.ISemanticAnalysisService>, Client.SemanticAnalysisService.ISemanticAnalysisService {
        
        public SemanticAnalysisServiceClient() {
        }
        
        public SemanticAnalysisServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SemanticAnalysisServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SemanticAnalysisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SemanticAnalysisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Service.TextAnalysisResult Analyze(string text) {
            return base.Channel.Analyze(text);
        }
        
        public System.Threading.Tasks.Task<Service.TextAnalysisResult> AnalyzeAsync(string text) {
            return base.Channel.AnalyzeAsync(text);
        }
    }
}
